In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("data_cleaning_sample.csv")

In [17]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
2  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3    David  22.0       Mumbai      M  david@example.com  12-11-2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5    Alice  25.0     New York      F  alice@example.com  01-05-2021
6  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [18]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False  False  False   False  False      False
2  False   True  False   False  False      False
3  False  False  False   False  False      False
4   True  False  False   False  False       True
5  False  False  False   False  False      False
6  False   True  False   False  False      False

In [19]:
df.isnull().sum()

Name         1
Age          2
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [20]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
1    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  David  22.0       Mumbai      M  david@example.com  12-11-2019
5  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [21]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1  Los Angeles      M    bob@example.com
2        Delhi      M    charlie@example
3       Mumbai      M  david@example.com
4        Delhi      F     eve@domain.com
5     New York      F  alice@example.com
6        Delhi      M    charlie@example

In [22]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
2  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
3    David  22.0       Mumbai      M  david@example.com  12-11-2019
4        0  28.0        Delhi      F     eve@domain.com           0
5    Alice  25.0     New York      F  alice@example.com  01-05-2021
6  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [23]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    26.0
3    22.0
4    28.0
5    25.0
6    26.0
Name: Age, dtype: float64

In [24]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
2  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
3    David  22.0       Mumbai      M  david@example.com  12-11-2019
4    David  28.0        Delhi      F     eve@domain.com  12-11-2019
5    Alice  25.0     New York      F  alice@example.com  01-05-2021
6  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [25]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
2  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
3    David  22.0       Mumbai      M  david@example.com  12-11-2019
4    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
5    Alice  25.0     New York      F  alice@example.com  01-05-2021
6  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [27]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
2  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3    David  22.0       Mumbai      M  david@example.com  12-11-2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5    Alice  25.0     New York      F  alice@example.com  01-05-2021
6  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [26]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [28]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
2  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3    David  22.0       Mumbai      M  david@example.com  12-11-2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [29]:
df.duplicated(subset=["Name", "Age"])

0    False
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [30]:
df["Name"].str.lower()

0      alice
1        bob
2    charlie
3      david
4        NaN
5      alice
6    charlie
Name: Name, dtype: object

In [31]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
2  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3    David  22.0       Mumbai      M  david@example.com  12-11-2019
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5    Alice  25.0     New York      F  alice@example.com  01-05-2021
6  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [32]:
df["City"].str.contains("delhi", case=False)

0    False
1    False
2     True
3    False
4     True
5    False
6     True
Name: City, dtype: bool

In [34]:
type(df["Email"].str.split("@"))

pandas.core.series.Series

In [35]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [bob, example.com]
2      [charlie, example]
3    [david, example.com]
4       [eve, domain.com]
5    [alice, example.com]
6      [charlie, example]
Name: Email, dtype: object

In [36]:
df2 = df.dropna().copy()

In [37]:
df2["Age"] = df2["Age"].astype(int)

In [38]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
1    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  David   22       Mumbai      M  david@example.com  12-11-2019
5  Alice   25     New York      F  alice@example.com  01-05-2021

In [39]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 5
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      object
 1   Age        4 non-null      int64
 2   City       4 non-null      object
 3   Gender     4 non-null      object
 4   Email      4 non-null      object
 5   Join Date  4 non-null      object
dtypes: int64(1), object(5)
memory usage: 224.0+ bytes

In [46]:
df2["Age Group"] = df2["Age"].apply(lambda x: "Adult" if x >= 25 else "Minor")

In [47]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
1    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  David   22       Mumbai      M  david@example.com  12-11-2019     Minor
5  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [48]:
def isminor(x):
    return "Adult" if x >= 25 else "Minor"

df2["Age Group"] = df2["Age"].apply(isminor)

In [49]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
1    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  David   22       Mumbai      M  david@example.com  12-11-2019     Minor
5  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [53]:
gender_map = {"M": "Male", "F": "Female"}
df2["Gender"] = df2["Gender"].map(gender_map)

In [54]:
df2

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
1    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  David   22       Mumbai    Male  david@example.com  12-11-2019     Minor
5  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult

In [60]:
df2["City"] = df2["City"].replace({"New York": "NY", "Mumbai": " New Mumbai"})

In [61]:
df2

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25        Delhi  Female  alice@example.com  01-05-2021     Adult
1    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  David   22   New Mumbai    Male  david@example.com  12-11-2019     Minor
5  Alice   25        Delhi  Female  alice@example.com  01-05-2021     Adult