In [114]:
import pandas as pd

In [115]:
df = pd.read_csv("bollywood_data.csv")

In [116]:
df

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Shushant Singh Rajput,Chichore,2019,Comedy,900,9.7
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [117]:
df.sort_values('IMDb')

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
10,Shushant Singh Rajput,Chichore,2019,Comedy,900,9.7

In [118]:
df.sort_values('IMDb', ascending=False)

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
10,Shushant Singh Rajput,Chichore,2019,Comedy,900,9.7
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [119]:
df2 = df.sort_values(['IMDb', 'Year']).copy()

In [120]:
#df2.reset_index(drop = True, inplace=True)

In [121]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Shushant Singh Rajput,Chichore,2019,Comedy,900,9.7
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [122]:
df2["Rank"] = df["IMDb"].rank(ascending=False, method="dense")

In [123]:
df2

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb,Rank
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
7,Hrithik Roshan,War,2019,Action,475,6.5,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,7.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,5.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,2.0
10,Shushant Singh Rajput,Chichore,2019,Comedy,900,9.7,1.0

In [124]:
df2 = df2[["Actor", "Year", "Genre", "Film", "IMDb", "BoxOffice(Cr)"]]

In [125]:
df2.sort_index()

,Actor,Year,Genre,Film,IMDb,BoxOffice(Cr)
0,Shah Rukh Khan,2023,Action,Pathaan,7.2,1050
1,Salman Khan,2017,Action,Tiger Zinda Hai,6.0,565
2,Aamir Khan,2016,Biography,Dangal,8.4,2024
3,Ranbir Kapoor,2022,Fantasy,Brahmastra,5.6,431
4,Ranveer Singh,2018,Historical,Padmaavat,7.0,585
5,Ayushmann Khurrana,2018,Thriller,Andhadhun,8.3,111
6,Rajkummar Rao,2018,Horror Comedy,Stree,7.5,180
7,Hrithik Roshan,2019,Action,War,6.5,475
8,Akshay Kumar,2019,Comedy,Good Newwz,7.0,318
9,Kartik Aaryan,2022,Horror Comedy,Bhool Bhulaiyaa 2,5.9,266
10,Shushant Singh Rajput,2019,Comedy,Chichore,9.7,900
11,Vicky Kaushal,2019,Action,Uri: The Surgical Strike,8.2,342