In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("bollywood_data.csv")

In [4]:
df

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Shushant Singh Rajput,Chichore,2019,Comedy,900,9.7
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df = df[df['IMDb']>6.0]

In [7]:
df

,Actor,Film,Year,Genre,BoxOffice(Cr),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Shushant Singh Rajput,Chichore,2019,Comedy,900,9.7
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [10]:
df.to_csv("data_updates.csv", index=False)

In [13]:
df = pd.read_json("data.json")

In [14]:
df

      name        lang
0   adarsh      python
1  krishna  javascript

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   lang    2 non-null      object
dtypes: object(2)
memory usage: 164.0+ bytes